// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#include "QueryObject.h"
#include "MutationsObject.h"

#include "graphqlservice/internal/Schema.h"

#include "graphqlservice/introspection/IntrospectionSchema.h"

#include <algorithm>
#include <array>
#include <functional>
#include <sstream>
#include <stdexcept>
#include <string_view>
#include <utility>
#include <vector>

using namespace std::literals;

namespace graphql {
namespace database {

Operations::Operations(std::shared_ptr<object::Query> query, std::shared_ptr<object::Mutations> mutation)
	: service::Request({
		{ service::strQuery, query },
		{ service::strMutation, mutation }
	}, GetSchema())
	, _query(std::move(query))
	, _mutation(std::move(mutation))
{
}

void AddTypesToSchema(const std::shared_ptr<schema::Schema>& schema)
{
	auto typeMutations = schema::ObjectType::Make(R"gql(Mutations)gql"sv, R"md()md"sv);
	schema->AddType(R"gql(Mutations)gql"sv, typeMutations);
	auto typeQuery = schema::ObjectType::Make(R"gql(Query)gql"sv, R"md()md"sv);
	schema->AddType(R"gql(Query)gql"sv, typeQuery);
	auto typeUser = schema::ObjectType::Make(R"gql(User)gql"sv, R"md()md"sv);
	schema->AddType(R"gql(User)gql"sv, typeUser);

	AddMutationsDetails(typeMutations, schema);
	AddQueryDetails(typeQuery, schema);
	AddUserDetails(typeUser, schema);

	schema->AddQueryType(typeQuery);
	schema->AddMutationType(typeMutations);
}

std::shared_ptr<schema::Schema> GetSchema()
{
	static std::weak_ptr<schema::Schema> s_wpSchema;
	auto schema = s_wpSchema.lock();

	if (!schema)
	{
		schema = std::make_shared<schema::Schema>(false, R"md()md"sv);
		introspection::AddTypesToSchema(schema);
		AddTypesToSchema(schema);
		s_wpSchema = schema;
	}

	return schema;
}

} // namespace database
} // namespace graphql
